#!/bin/bash



wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get -y install jenkins curl python maven subversion git xvfb htop maven
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:webupd8team/java
oracle-java-7-installer
